apiVersion: security.k8smgmt.io/v3
kind: ClusterNetworkPolicyRule
metadata:
  name: jan19-r1
  project: giri
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/jan19-r1/cluster-wide.yaml
    options: {}
    type: Yaml
  version: v1
