apiVersion: 'cilium.io/v2'
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: 'cassandra-block'
spec:
  endpointSelector:
    matchLabels:
      app.kubernetes.io/instance: app-cassandra
  ingress:
  - fromEndpoints:
    - matchLabels:
        org: empire
    toPorts:
    - ports:
      - port: "80"
