apiVersion: security.k8smgmt.io/v3
kind: NetworkPolicyProfile
metadata:
  name: new
  project: giri
spec:
  installationParams:
    policyEnforcementMode: default
  sharing:
    enabled: true
    projects:
    - name: ram-project
  version: v1
