apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: varun-ns-14nov
  labels:
    app: busybox
spec:
  containers:
  - name: busybox
    image: busybox:1.28
    command: ["sleep", "3600"]
  restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: busybox-service
  namespace: varun-ns-14nov
spec:
  selector:
    app: busybox
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP