apiVersion: infra.k8smgmt.io/v3
kind: Cluster
metadata:
  labels:
    relayRegion: us-east-1
  name: giri-20nov-az1
  project: giri
spec:
  blueprintConfig:
    name: default-aks
  cloudCredentials: giri-aks
  config:
    kind: aksClusterConfig
    metadata:
      name: giri-20nov-az1
    spec:
      managedCluster:
        apiVersion: "2024-01-01"
        identity:
          type: SystemAssigned
        location: centralindia
        properties:
          apiServerAccessProfile:
            enablePrivateCluster: false
            enablePrivateClusterPublicFQDN: false
          disableLocalAccounts: false
          dnsPrefix: giri-20nov-az1-dns
          enablePodSecurityPolicy: false
          enableRBAC: true
          kubernetesVersion: 1.30.0
          networkProfile:
            loadBalancerSku: standard
            networkPlugin: kubenet
            networkPolicy: calico
          powerState:
            code: Stopped
        sku:
          name: Base
          tier: Free
        type: Microsoft.ContainerService/managedClusters
      nodePools:
      - apiVersion: "2024-01-01"
        name: primary
        properties:
          count: 3
          enableAutoScaling: true
          maxCount: 3
          maxPods: 110
          minCount: 2
          mode: System
          orchestratorVersion: 1.30.0
          osType: Linux
          type: VirtualMachineScaleSets
          vmSize: Standard_B2ms
        type: Microsoft.ContainerService/managedClusters/agentPools
      resourceGroupName: giri
  type: aks
