apiVersion: gitops.k8smgmt.io/v3
kind: Pipeline
metadata:
  name: pipeline
  project: giri
spec:
  active: true
  stages:
  - config:
      destinationRepo: {}
      gitToSystemSync: true
      includedResources:
      - name: '*'
      sourceAsDestination: true
      sourceRepo:
        repository: giri-stage
        revision: main
      systemToGitSync: true
    name: test
    type: SystemSync
  triggers:
  - config:
      repo:
        provider: Github
        repository: giri-stage
        revision: main
    name: test
    type: Webhook
