apiVersion: apps.k8smgmt.io/v3
kind: WorkloadTemplate
metadata:
  name: rabbitmq-temp
  project: giri
spec:
  artifact:
    artifact:
      chartName: rabbitmq
      repository: default-bitnami
    options:
      maxHistory: 10
      timeout: 5m0s
    type: Helm
