apiVersion: opa.k8smgmt.io/v3
kind: OPAConstraintTemplate
metadata:
  labels:
    rafay.dev/opa: template
  name: ns-required-labels
  project: giri
spec:
  artifact:
    artifact:
      paths:
      - name: file://artifacts/ns-required-labels/ns-label-opa-template.yaml
    options: {}
    type: Yaml
