apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: qa-automation
  namespace: default
spec:
  encryptedData:
    credentials.password: AQCHMSs3Ky0tc4M5uZ3lj8FVlA55OMCbfRvMpYLzMPUo+gurXMGH92H0dyaE2qwanClmzVA4fBIzuUl076uBctopCrre+cPMADuEIf8e45Zs6x5/26gvhmROvLSPdmbhTWR93u6+je9DeFVG7p8WqdzfZUt8oRZP0BKhccUm67JHec+Znu9GjRARhdCskIS+VxXExEVd553sPjYJ16m79ujm0mhYIiXhs1vWx3njI9ZdeFbmRI/o65kNa7LShaWUOlC3MXekQFPGUBdYQtVVtidYAgeH4c3te08Y5IwjVgPZi8sCr3hcRiqViVbaBkPc6xo/cnrHpB75m0IG10EiYGT9NejB3X5hcg5CJLkW/5nwYd6049duxf/8m+BuonTg8dqIsCdOJpBgNOFkR7takkLkDqeMuiKysqo=
  template:
    metadata:
      creationTimestamp: null
      name: qa-automation
      namespace: default

