apiVersion: cost.k8smgmt.io/v3
kind: CostProfile
metadata:
  name: nov-onprem
  project: giri
spec:
  installationParams:
    other:
      cpu: "10"
      gpu: "30"
      memory: "20"
  providerType: other
  version: version1
